version: "3"

services:
  monitor-ssl-expire:
    container_name: monitor-ssl-expire
    image: monitor-ssl-expire:v20230519-v1684473706
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_ENV: "prod"
      APP_PORT: "8080"
      APP_HOST: "0.0.0.0"
      APP_LOG_LEVEL: "INFO"
      SSL_EXPIRE_DAYS: "30"

    volumes:
      - "/data/docker-compose/monitor-ssl-expire/logs:/data/monitor-ssl-expire/logs"

    networks:
      - monitor-ssl-expire

networks:
  monitor-ssl-expire:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
