deployment:
  appLog:
    enabled: true
  ports:
    - containerPort: 8080
      protocol: TCP
  healthCheck:
    path: /healthz
    port: TCP-8080
  env:
    enabled: true
    default:
      # 全局的环境变量
      - name: APP_ENV
        value: "prod"
      - name: APP_PORT
        value: "8080"
      - name: APP_HOST
        value: "0.0.0.0"
      - name: APP_LOG_LEVEL
        value: "INFO"
      - name: SSL_EXPIRE_DAYS
        value: "30"      

# 服务配置
service:
  config:
    - targetPort: 8080
      advanced:
        enabled: false
      ingress:
        enabled: true
        vhosts:
          # 配置需要发布的服务的域名
          # appType决定了域名发布为公网还是内网域名，只有两个可选值：internal、external
          - appType: internal
            # 用双引号引起来表示字符串。如果不用双引号，chart包渲染可能会提示类型不匹配问题
            # domainType决定了发布为哪个域名后缀，有三个可选值：default、portal(门户网站)、bothway(双向认证)
            domainType: "default"
            # true：开启https双向认证，false：关闭https双向认证
            # domainType为bothway时这个值要设置为true
            verifyClientCert: false
            # 此项用于特定需求需要自定义域名前缀的情况。
            # 如果是发布网关项目，则下面domainPrefixes直接注释掉，会使用下面gateways下定义的domainPrefixes
            domainPrefixes:
              - monitor-ssl-expire
          - appType: external
            domainType: "default"
            verifyClientCert: false
            domainPrefixes:
              - monitor-ssl-expire
